
#██╗░░░██╗███████╗██╗░░██╗██╗████████╗██╗░░░██╗░░░██████╗░░██╗░░░░░░░██╗
#██║░░░██║██╔════╝╚██╗██╔╝██║╚══██╔══╝╚██╗░██╔╝░░░██╔══██╗░██║░░██╗░░██║
#╚██╗░██╔╝█████╗░░░╚███╔╝░██║░░░██║░░░░╚████╔╝░░░░██████╔╝░╚██╗████╗██╔╝
#░╚████╔╝░██╔══╝░░░██╔██╗░██║░░░██║░░░░░╚██╔╝░░░░░██╔═══╝░░░████╔═████║░
#░░╚██╔╝░░███████╗██╔╝╚██╗██║░░░██║░░░░░░██║░░░██╗██║░░░░░░░╚██╔╝░╚██╔╝░
#░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░╚═╝░░░░░░╚═╝░░░╚═╝╚═╝░░░░░░░░╚═╝░░░╚═╝░░
# Разработчик: github.com/SoMax1soft  
# Телеграм канал: https://t.me/vexityai
# Сайт: Vexity.pw
#
# Права:
# vexity.admin - /vexity reload, /vexity reinstall, /vexity ai status, /vexity ai reload
# vexity.staff - /vexity reports и уведомления о варнах/финальных наказаниях
# vexity.bypass - байпас задержек, фильтра ссылок, allowed-symbols и AI-проверки
# vexity.color - разрешает цветовые коды в чате
#
chat:
  debug: false # Включить дебаг логи чата (CommandFilterListener, ChatFilter)
  mode: "DEFAULT" # DEFAULT / RESTRICTED / SOFT
  # RESTRICTED - режим чата где используется только глобальный чат
  # DEFAULT - режим чата где используются все чаты
  # SOFT - Vexity не форматирует чат и не применяет задержку/allowed-symbols, только проверяет ссылки и ИИ в обычном чате/Chatty/PromisedChat/других чат-плагинах
  delay:
    groups:
      default: 3 # кол-во секунд задержки
    priorities:
      default: 3 # если  у игрока 2 доната и 1 выше другого то он получит задержку высшего доната
  delay-message: "&e🔥 ┃&f Вы &eслишком быстро&f пишите! Подождите еще &c {TIME} сек." # Сообщение о задержке
  local: "&e🔥 &7┃ &f{PREFIX} &f{PLAYER}{SUFFIX} &8✎&f {MESSAGE}"
  global: "&c🔥 &7┃ &f{PREFIX} &f{PLAYER}{SUFFIX} &8✎&f {MESSAGE}"
  block-radius: 150 # Радиус локал чата

allowed-symbols:
  # Стандартные символы для новых игроков (без латиницы)
  standard: ' ёЁйцукенгшщзхъфывапролджэячсмитьбюіЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮІїЇєЄґҐ0123456789!@#$%^&*()_+-=[]{}|;:,.<>/?~`\'
  # Расширенные символы для игроков с наигранным временем (кириллица + латиница + спецсимволы)
  # Все остальные символы (фэнси шрифты, юникод и т.д.) будут заменены на *
  advanced: ' abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZёЁйцукенгшщзхъфывапролджэячсмитьбюіЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮІїЇєЄґҐ0123456789!@#$%^&*()_+-=[]{}|;:,.<>/?~`"'
# Поддерживает плейсхолдеры PLACEHOLDERPI
hover:
  enabled: true # Отключить ховер при наведении на ник в чате
  lines:
    - " &r"
    - " &3&n|§f Имя: &#00C1FF%player_name%"
    - " &3&n|§f Наиграно: &a%statistic_hours_played% часов."
    - " &3|§f Баланс: §b%playerpoints_points% рублей."
    - " &r"
links:
  enabled: true
  auto-style:
    enabled: true
    color: "RED" # RED, BLUE, GREEN или цветовой код вроде &c
    underline: true
    open-on-click: true
  whitelist:
    - "https://mlsac.net" # kaif
    - "https://vexity.pw" # top
  message: "&e🔥 &7| &cСсылки запрещены! &7(Разрешены только из белого списка)"
messages:
  chat-delay-message: "&e🔥 &7| &fПодожди! Что-бы &eнаписать в чат&f вы должны отыграть &e5 минут&f на сервере, осталось &e{MINUTES} "
  advanced-delay-message: "&e🔥 &7| &fПодожди! Что-бы &eнаписать в чат&f вы должны отыграть &e5 минут&f на сервере, осталось &c{TIME}"
  command-delay-message: "&e🔥 &7┃&f Вы &x&F&A&B&3&4&1слишком быстро&f пишите! Подождите еще &c{TIME} сек."
command-delay:
  # Пример: задержка на команду /home
  # home:
  #   aliases:
  #     - "cmi home"
  #   cooldown:
  #     default: 30
  #     vip: 15
  #     admin: 5
  # Пример: задержка на команду /tpa
  # tpa:
  #   aliases:
  #     - "cmi tpa"
  #   cooldown:
  #     default: 60
  #     vip: 30
newbie-commands:
  delay: 300 # задержка в секундах для новичков на эти команды (отдельно от chat-delay)
  list:
    - "/cmi msg"
    - "/msg"
    - "/reply"
    - "/cmi reply"
    - "/m"
    - "/r"
    - "/w"
    - "/tell"
autoMessage:
  enable: false
  random: true
  messageInterval: 300
  messages:
    1:
      - "&r "
      - " Автоматическое сообщение"
      - " Vexity AI - ваш ИИ модератор"
      - " Telegram: t.me/vexityai"
      - "&r "  
    2:
      - "&r "
      - " Автоматическое сообщение"
      - " Vexity Chat - лучший плагин на чат"
      - " Telegram: t.me/vexityai"
      - "&r "
time:
  switch-to-advanced: 600  # Время в секундах (600 сек = 10 минут)
  chat-delay: 300 # Время в секундах до разрешения чата (300 сек = 5 минут)

# Настройки ИИ Модерации "Vexity-AI"
vexityai:
  enabled: true
  debug: true
  # URL Vexity-AI бэкенда (инференс + лицензии)
  api-url: "https://api.vexity.pw"
  # Лицензионный ключ. Получить в админ-панели Vexity. Без него ИИ не работает.
  license-key: "vex_dbcdab5ee65bb0a03e1dfa0979a0018c" # БЕСПЛАТНЫЙ КЛЮЧ ДЛЯ ВСЕХ КОНЧАЕТСЯ 07.06.2026
  notify-message: "&f&l[Vexity] &fИгрок &e{player} &fнарушил правило &c{rule}.&f Наказание выдано!"
  staff-warning-message: "&f&l[Vexity] &e{player} &fполучил варн &c{warning}/{max_warnings}&f по правилу &c{rule}&f."
  
  # Прогрессивная система наказаний (варны)
  progressive:
    expire-time: "30m" # Через сколько времени сбросится счетчик нарушений
    rules:
      "1": # Категория ИИ 1 (Оск. игроков) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Оскоребление игроков"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило Оскорбление игроков 1/2"
          2: "tempmute {player} &fВы нарушили правило Оскорбление игроков 2/2 (vexity-ai)"
      "2": # Категория ИИ 2 (Оск. родни) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Оскорбление родни"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило Оскорбление родни 1/2"
          2: "tempmute {player} Вы нарушили правило Оскорбление родни 2/2 (vexity-ai)"
      "3": # Категория ИИ 3 (Оск. администрации) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Оскорбление администрации"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило Оскорбление администрации 1/2"
          2: "tempmute {player} нарушили правило Оскорбление администрации 2/2 (vexity-ai)"
      "4": # Категория НЕ ИИ 4 (Спам/Капс) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Спам/Капс"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило - Спам/Капс 1/2"
          2: "tempmute {player} нарушили правило - Спам/Капс 2/2 (vexity-local)"
      "5": # Категория ИИ 5 (Оск. сервера) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Оскорбление сервера"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило - Оскорбление сервера 1/2"
          2: "tempmute {player} Вы нарушили правило - Оскорбление сервера 2/2 (vexity-ai)"
      "6": # Категория ИИ 6 (Призыв к суициду) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Призыв к суициду"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило - Призыв к суициду 1/2"
          2: "tempmute {player} Вы нарушили правило - Призыв к суициду 2/2 (vexity-ai)"
      "7": # Категория ИИ 7 (Разжигание межнациональной розни) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Разжигание межнациональной розни"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило - Разжигание межнациональной розни 1/2"
          2: "tempmute {player} Вы нарушили правило - Разжигание межнациональной розни 2/2 (vexity-ai)"
      "8": # Категория ИИ 8 (Реклама/Продвижение серверов/читов) НАЗВАНИЕ КАТЕГОРИЙ НЕ МЕНЯТЬ МОЖНО МЕНЯТЬ ТОЛЬКО RULE-ID
        rule-id: "Реклама/Продвижение серверов/читов"
        max-warnings: 2
        levels:
          1: "{NOTIFY}&f&l[Vexity] &fВы нарушили правило - Реклама/Продвижение серверов/читов 1/2"
          2: "tempmute {player} Вы нарушили правило - Реклама/Продвижение серверов/читов 2/2 (vexity-ai)"
  # Классический детектор (для категории 4)
  anti-caps:
    enabled: true
    min-length: 5 # Минимальная длина сообщения для проверки
    percent: 100 # Процент капса для срабатывания
  
  anti-flood:
    enabled: true
    max-repeating-chars: 4 # ааааа - можно, аааааа - нельзя
    min-similarity: 0.95 # Насколько похожи должны быть сообщения (0.8 = 80%)
